#!/bin/sh
#配置时区
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system
#配置宽带拨号
uci set network.wan.proto="pppoe"
uci set network.wan.username="15920019291@139.gd"
uci set network.wan.password="019291"
uci set network.lan.ipaddr='10.0.0.1'
uci commit network
#配置WIFI
uci set wireless.radio0.disabled='1'
uci set wireless.radio1.disabled='0'
uci set wireless.radio1.ssid='OVO'
uci set wireless.radio1.encryption='psk2'
uci set wireless.radio1.key='WIFI8520.0'
uci commit wireless
wifi
#修改密码（空格）
#sed -i '1i\root:$1$McPtUJaL$M47t/nUbjYrWraS5NgvOx0:18552:0:99999:7:::' /etc/shadow
#默认配置操作详见： https://openwrt.org/docs/guide-developer/uci-defaults
exit 0
